import type { Customer, Conversation, Message, Prisma, QuickAction, Settings, User } from "@prisma/client";
export function userDto(user:User & {queueAccess?:{queue:string}[]},permissions:string[]=[]){return {id:user.id,name:user.name,username:user.username,role:user.role,queues:user.queueAccess?.map(q=>q.queue)??[],permissions,active:user.active,createdAt:user.createdAt.toISOString(),updatedAt:user.updatedAt.toISOString()};}
export function customerDto(c:Customer & {conversations?:{assignedStaffId:string|null}[]}){return {id:c.id,clientCode:c.clientCode,name:c.name,username:c.username,clientType:c.clientType,status:c.status,firstSeenAt:c.firstSeenAt.toISOString(),lastSeenAt:c.lastSeenAt.toISOString(),evaluationExpiresAt:c.evaluationExpiresAt?.toISOString(),convertedAt:c.convertedAt?.toISOString()??null,convertedBy:c.convertedById,assignedStaffId:c.conversations?.[0]?.assignedStaffId??null,createdAt:c.createdAt.toISOString(),updatedAt:c.updatedAt.toISOString()};}
export function conversationDto(c:Conversation){return {id:c.id,customerId:c.customerId,status:c.status,assignedStaffId:c.assignedStaffId,createdAt:c.createdAt.toISOString(),updatedAt:c.updatedAt.toISOString(),lastMessageAt:c.lastMessageAt?.toISOString()};}
type MessageWithAttachments=Message&{attachments?:{id:string;originalName:string;mimeType:string;sizeBytes:number}[]};
export function messageDto(m:MessageWithAttachments){return {id:m.id,conversationId:m.conversationId,senderType:m.senderType,senderId:m.senderId,messageType:m.messageType,text:m.text??undefined,clientMessageId:m.clientMessageId??undefined,createdAt:m.createdAt.toISOString(),deliveredAt:m.deliveredAt?.toISOString(),readAt:m.readAt?.toISOString(),attachments:m.attachments?.map(a=>({id:a.id,originalName:a.originalName,mimeType:a.mimeType,sizeBytes:a.sizeBytes}))??[]};}
export const settingsDto=(s:Settings)=>({businessName:s.businessName,welcomeMessage:s.welcomeMessage,newClientEvaluationDays:s.newClientEvaluationDays,archiveEnabled:s.archiveEnabled,archiveRetentionDays:s.archiveRetentionDays,supportOnline:s.supportOnline});
export const quickActionDto=(q:QuickAction)=>({id:q.id,label:q.label,emoji:q.emoji??undefined,message:q.message,enabled:q.enabled,order:q.order,visibility:q.visibility});
export const pagination=(query:Record<string,unknown>)=>{const page=Math.max(1,Number(query.page??1));const pageSize=Math.min(100,Math.max(1,Number(query.pageSize??query.limit??25)));return{page,pageSize,skip:(page-1)*pageSize};};
export const auditDto=(a:{id:string;actorId:string|null;actorName:string|null;action:string;targetType:string|null;targetId:string|null;ipAddress:string|null;metadata:Prisma.JsonValue|null;createdAt:Date})=>({id:a.id,actorId:a.actorId??undefined,actorName:a.actorName??undefined,action:a.action,targetType:a.targetType??undefined,targetId:a.targetId??undefined,ipAddress:a.ipAddress??undefined,metadata:(a.metadata??undefined) as Record<string,unknown>|undefined,createdAt:a.createdAt.toISOString()});
